# Generated by Django 2.1.7 on 2019-03-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('data_wprowadzenia_ceny', models.DateTimeField(auto_now_add=True, verbose_name='obowiązuje od')),
            ],
        ),
        migrations.CreateModel(
            name='ListaObslugujacych',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przypisania', models.DateTimeField(auto_now_add=True, verbose_name='przypisano')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPozycji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pozycja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0)),
                ('poczatek_uzywania', models.DateTimeField(verbose_name='początek używania')),
                ('koniec_uzywania', models.DateTimeField(verbose_name='koniec używania')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wyplata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_nowe', models.BooleanField(default=True)),
                ('data_zlozenia', models.DateTimeField(auto_now_add=True, verbose_name='złożono')),
                ('pracownik_skladajacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Pracownik')),
            ],
        ),
        migrations.AddField(
            model_name='pozycja',
            name='sprzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Sprzet'),
        ),
        migrations.AddField(
            model_name='listapozycji',
            name='pozycja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Pozycja'),
        ),
        migrations.AddField(
            model_name='listapozycji',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Zamowienie'),
        ),
        migrations.AddField(
            model_name='listaobslugujacych',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Pracownik'),
        ),
        migrations.AddField(
            model_name='listaobslugujacych',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Zamowienie'),
        ),
        migrations.AddField(
            model_name='cena',
            name='sprzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.Sprzet'),
        ),
    ]
